name: Run Script in Alpine VM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4

    # - name: Set up Docker
    #   run: |
    #       sudo apt-get update
    #       sudo apt-get install -y docker.io

    - name: Build
      run: |
        cd devtools/docker
        chmod +x ./createimage.sh
        ./createimage.sh
